name: Dcard Crawler

on:
  workflow_dispatch:   # 可以手動觸發
  schedule:
    - cron: '0 18 * * *'  # 每天 18:00 執行

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager undetected-chromedriver keyboard pandas tqdm

      - name: Debug: list files
        run: ls -R

      - name: Run Dcard crawler
        run: |
          mkdir -p data
          python scripts/Dcard_crawler.py data/
        working-directory: ${{ github.workspace }}

      - name: Upload crawled data
        uses: actions/upload-artifact@v4
        with:
          name: dcard-data
          path: data/
