name: Dcard Crawler

on:
  schedule:
    - cron: '0 18 * * *'  # 每天下午 6 點執行
  workflow_dispatch:     # 手動觸發也可以

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: 取得 repo
      uses: actions/checkout@v3

    - name: 安裝 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安裝套件
      run: |
        pip install --upgrade pip
        pip install undetected-chromedriver selenium webdriver-manager pandas keyboard tqdm

    - name: 執行爬蟲
      run: |
        python scripts/Dcard爬蟲.py

    - name: 上傳 CSV
      uses: actions/upload-artifact@v3
      with:
        name: dcard-csv
        path: '*.csv'
