name: Dcard 爬蟲 & CSV 清理

on:
  workflow_dispatch:  # 手動觸發
  schedule:
    - cron: '0 18 * * *'  # 每天 18:00 自動執行

jobs:
  crawl_and_clean:
    runs-on: ubuntu-latest

    steps:
      # 1. 取得 repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安裝 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. 安裝套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager undetected-chromedriver pandas tqdm keyboard

      # 4. 執行爬蟲程式
      - name: Run Dcard crawler
        run: |
          python scripts/Dcard爬蟲.py

      # 5. 清理 CSV
      - name: Clean CSV files
        run: |
          python scripts/clean_csv.py

      # 6. 上傳結果 CSV 為 artifact
      - name: Upload CSV files
        uses: actions/upload-artifact@v4
        with:
          name: dcard-csv
          path: |
            *.csv
